---
title: "AnVIL CoFests! 2025"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: Description about Course/Book.
favicon: assets/AnVIL_style/anvil_favicon.ico
---

# What are CoFests!? {-}

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_cofest_definition.Rmd",
  repo_name = "jhudsl/AnVIL_Template",
  branch = "cofestChunks",
  remove_h1 = TRUE
)
```

## Previous AnVIL CoFests! {- .unlisted}

```{r echo=FALSE, out.width = "100%", fig.alt = "ACC 2024 CoFest! Images", fig.link = "https://jhudatascience.org/AnVIL_CoFests_2024/"}
ottrpal::include_slide("https://docs.google.com/presentation/d/1vbIwwMYnG-jvtKQ23vH0UkJeei-Ze_m3FB4seG_yMnk/edit?slide=id.g3776c8c71f0_2_138#slide=id.g3776c8c71f0_2_138")
```

[ACC 2024 at Cold Spring Harbor Laboratories](https://jhudatascience.org/AnVIL_CoFests_2024/)

## AnVIL Collection {- .unlisted}

Please check out our full collection of AnVIL and related resources: https://hutchdatascience.org/AnVIL_Collection/
