# Polygenic Risk Score (PRS) Analysis in AnVIL

Led by: Matthew Lebo, Harvard Medical School

AnVIL Outreach coordinator: Elizabeth Humphries

## About

This track, run by the AnVIL Clinical Resource team, will consist of both an overview and a hands-on workshop to provide individuals with an understanding of polygenic scores and how to run and evaluate them in AnVIL. First, we will level-set by providing an overview of the current state of polygenic analysis, with a focus on polygenic risk scores (PRS). Next, we will jointly work with participants to run PRS analyses in AnVIL using the WDL framework. These tasks will increase in complexity in terms of analytical components of the workflow, with the goal of enabling users to run the WDL on their own. We will also engage with participants to get feedback and create user-friendly documents to enable processing of this workflow once published to the broader community. Finally, we will work with more advanced users to generate a new WDL focused on the evaluation of PRS among a cohort of individuals.

Participants are not required to supply their own data, as publicly available data and an AnVIL workspace will be provided as part of the CoFest track. Users who are interested in running the analyses on their own data are welcome, but should have their own workspace in which to run the analyses.

## Workspace

The workspace for this track can be found at [https://anvil.terra.bio/#workspaces/mgb-lmm-clinical/AnVIL_CoFest2024_PRS_Analysis](https://anvil.terra.bio/#workspaces/mgb-lmm-clinical/AnVIL_CoFest2024_PRS_Analysis). This is a private workspace, so you will have to be given permission in order to view it. Participants in this tract should contact Elizabeth Humphries if they cannot access the workspace.